---
resources:
- name: website
  type: git
  source:
    uri: https://github.com/UF-ACE/devops-demo
    branch: master

jobs:
- name: test
  plan:
  - get: website
    trigger: true
  - task: run-unit
    file: project/ci/test.yml