---
resources:
- name: website
  type: git
  icon: github-circle
  source:
    uri: https://github.com/UF-ACE/devops-demo

jobs:
- name: test
  plan:
  - get: website
    trigger: true
  - task: run-test
    file: website/project/ci/test.yml

- name: build
  plan:
  - get: website
    passed: [test]
    trigger: true
  - task: run-build
    file: website/project/ci/test.yml