---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: karlkfi/concourse-dcind
    tag: 'latest'

inputs:
- name: website

run:
  path: entrypoint.sh
  args:
    - bash
    - -eux
    - website/project/ci/scripts/build